### ISSUE TITLE
CentOS 7: Avoid SELinux protection (Error 503) with enforcing mode 

### ISSUE THREAD

**Issue by syndrome5** [RapidScada/scada#51]
After the Linux installation, the 503 error appears (on CentOS 7).

To avoid this problem WITHOUT deactivate SELinux : 
1) Download the attached file [httpdPolicy.zip](https://github.com/RapidScada/scada/files/1837624/httpdPolicy.zip) and unzip it to get the .pp file
2) Launch this commandline : `semodule -i httpdPolicy.pp`
3) Current mode for SELinux `sestatus` would be "enforcing" & reboot

**Comment by 2mik** [comment]
Hi,
Thank you for the useful notice.
I moved this information to our forum https://forum.rapidscada.org/?topic=centos-7-avoid-selinux-protection-error-503-with-enforcing-mode because the forum is the knowledge base of Rapid SCADA. I would like to receive more information about this issue from different users to decide if we should include this instructions into the installation package.
